[build]
  publish = "dist/spa"
  command = "npm run quick:build"
  functions = "netlify/functions"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"
