[build]
  command = "npm run build:netlify"
  functions = "netlify/functions"
  publish = "dist/spa"

[build.environment]
  NODE_VERSION = "20"

[functions]
  external_node_modules = ["express", "sqlite3", "multer", "serverless-http"]
  node_bundler = "esbuild"

# API routes - FORCE redirect
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Explicit React routes - FORCE to index.html
[[redirects]]
  from = "/dubai-businesses"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/dubai-businesses/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/business-directory"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/business-directory/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/business/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/report"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/report/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200
  force = true

# Catch-all SPA fallback - MUST BE LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Minimal headers to avoid conflicts
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
