[build]
  publish = "dist/spa"
  command = "npm run quick:build"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"