name: dubai-businesses-platform
services:
  - name: web
    source_dir: /
    github:
      repo: your-username/your-repo-name
      branch: main
      deploy_on_push: true
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: PORT
        value: "8080"
        scope: RUN_AND_BUILD_TIME
      - key: GOOGLE_PLACES_API_KEY
        value: ${GOOGLE_PLACES_API_KEY}
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: NETLIFY_ACCESS_TOKEN
        value: ${NETLIFY_ACCESS_TOKEN}
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: NETLIFY_SITE_ID
        value: ${NETLIFY_SITE_ID}
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        scope: RUN_AND_BUILD_TIME
    build_command: |
      npm ci
      npm run build
    dockerfile_path: Dockerfile

databases:
  - name: db
    engine: PG
    version: "14"
    size: basic
    num_nodes: 1
    production: false

workers:
  - name: photo-processor
    source_dir: /
    github:
      repo: your-username/your-repo-name
      branch: main
      deploy_on_push: true
    run_command: node server/workers/photo-processor.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        scope: RUN_AND_BUILD_TIME
      - key: GOOGLE_PLACES_API_KEY
        value: ${GOOGLE_PLACES_API_KEY}
        scope: RUN_AND_BUILD_TIME
        type: SECRET
